#!/bin/sh
# chkconfig: 345 99 01
# description: Auto-starts mir-http-repo
# /etc/init.d/springboot-redis-mysql-rabbitmq
# springboot-redis-mysql-rabbitmq auto-start
# Source function library.
if [ -f /etc/rc.d/init.d/functions ]; then
  . /etc/rc.d/init.d/functions
elif [ -f /lib/lsb/init-functions ]; then
  . /lib/lsb/init-functions
  . /etc/rc.status
  rc_reset
fi


RETVAL=0
export CATALINA_HOME=/opt/server/springboot-redis-mysql-rabbitmq/
export CATALINA_BASE=/opt/server/springboot-redis-mysql-rabbitmq/
export CONFIG_DIR=/opt/server/springboot-redis-mysql-rabbitmq/config
export MIR_USER=root
export PIDFILE=springboot-redis-mysql-rabbitmq.pid
export RUN_LOG=/var/log/springboot-redis-mysql-rabbitmq/run.log
start()
{
        if [ -f $CATALINA_HOME/bin/startup.sh ];
          then            
            echo $"Starting springboot-redis-mysql-rabbitmq"
             su - $MIR_USER -c "sh $CATALINA_HOME/bin/startup.sh $CONFIG_DIR/application.properties  >$RUN_LOG 2>&1 &"    
            
            sleep 2 
            su - $MIR_USER -c "ps -fwwu $MIR_USER | grep springboot-redis-mysql-rabbitmq|grep -v grep | grep -v PID | awk '{print \$2}' > $CATALINA_HOME/springboot-redis-mysql-rabbitmq.pid &"

            RETVAL=$?
            echo " OK"
            return $RETVAL
        fi
}
stop()
{        
      if [ -s $CATALINA_HOME/springboot-redis-mysql-rabbitmq.pid ];
          then            
            echo $"Stopping springboot-redis-mysql-rabbitmq"
            RETVAL=$?
            sleep 1
            kill -9 `cat $CATALINA_HOME/springboot-redis-mysql-rabbitmq.pid` && rm -rf $CATALINA_HOME/springboot-redis-mysql-rabbitmq.pid
            echo " OK"
            return $RETVAL
         else
           echo $"springboot-redis-mysql-rabbitmq is not runing! "
        fi
}
case "$1" in
 start)  
        start
        ;;
 stop)   
        stop
        ;;
restart)
         echo $"Restaring springboot-redis-mysql-rabbitmq"                
          stop            
         sleep 5                 
          start           
         ;;              
 *) 
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit $RETVAL
